### ISSUE TITLE
stray tab at the end of most of the Makefile's

### ISSUE THREAD

**Issue by HinTak** [Laidout/laidout#1]
You have a stray tab at the end of almost all the Makefile's . emacs does not like that.

(tabs are meaningful in makefiles to indicate the body of a make target).

**Comment by tomlechner** [comment]
Fixed! (I use vim)

**Comment by HinTak** [comment]
Don't want to get into a vim vs emacs war :-). I have set up syntax-highlighting in emacs to default on, which shows tab's in color. vim probably can do that too.
