### ISSUE TITLE
Laidout

### ISSUE THREAD

**Issue by fvillavi** [Laidout/laidout#19]
Laidout on linux Mint 64bit do  not start. send a message: laidout-0.095
Violación de segmento (`core' generado)

**Comment by tomlechner** [comment]
.095 is really old. Does a newer version crash? Best versions should be:
[EDIT!] oops, mixed up the links, corrected now:
 - the dev appimage: https://github.com/Laidout/laidout/releases/tag/continuous
 - or 0.097 (this one is getting old too): https://github.com/Laidout/laidout/releases/tag/0.097

**Comment by tomlechner** [comment]
Are you having the same crash with newer versions? I'll close if not.

**Comment by tomlechner** [comment]
Hoping it's working now...(?)
