### ISSUE TITLE
fedora build tips

### ISSUE THREAD

**Issue by HinTak** [Laidout/laidout#2]
laxkit needs a patch - please feel free to correct/improve that:

https://github.com/tomlechner/laxkit/issues/1#issuecomment-211601965

I'd also like to comment that laidout likes to have laxkit as a sub-directory - it might be useful to add that as a git submodule - i.e. change the laidout git build advice from two separate git checkout to , hooking laxkit as a git submodule (a small addition), and update the top level README to do that instead.

```
cd laidout
git clone http://github.com/tomlechner/laxkit.git laxkit
```

to 

```
 cd laidout
git submodule init --update
```

**Comment by HinTak** [comment]
On Fedora,

```
$ ldd ./src/laidout | grep '=>' | cut -f 2 -d '>' | cut -f 2 -d ' ' | xargs rpm -qf | sort | uniq | perl -p -e 's(-[^-]+-[^-]+$)(\n)'
avahi-libs
bzip2-libs
cairo
cups-libs
dbus-libs
elfutils-libelf
elfutils-libs
expat
fontconfig
freetype
ftgl
glib2
glibc
gmp
gnutls
GraphicsMagick
GraphicsMagick-c++
graphite2
harfbuzz
imlib2
keyutils-libs
krb5-libs
lcms2
libattr
libcap
libcom_err
libdrm
libffi
libgcc
libgcrypt
libgomp
libgpg-error
libICE
libidn
libpng
libselinux
libSM
libstdc++
libtasn1
libtool-ltdl
libuuid
libwayland-client
libwayland-server
libX11
libXau
libxcb
libXdamage
libXext
libXfixes
libXft
libXi
libXrender
libxshmfence
libXxf86vm
mesa-libEGL
mesa-libgbm
mesa-libGL
mesa-libglapi
mesa-libGLU
ncurses-libs
nettle
nss-softokn-freebl
openssl-libs
p11-kit
pcre
pixman
readline
sqlite-libs
systemd-libs
xz-libs
zlib
```

```
$ ldd ./src/laidout | grep '=>' | cut -f 2 -d '>' | cut -f 2 -d ' ' | xargs rpm -qf | sort | uniq | perl -p -e 's(-libs-)(-);s(-[^-]+-[^-]+$)(-devel\n)'  | xargs rpm -q | perl -p -e 's(-[^-]+-[^-]+$)(\n)'  | sort | uniq
bzip2-devel
cairo-devel
cups-devel
dbus-devel
elfutils-devel
elfutils-libelf-devel
expat-devel
fontconfig-devel
freetype-devel
ftgl-devel
glib2-devel
glibc-devel
gmp-devel
gnutls-devel
GraphicsMagick-c++-devel
GraphicsMagick-devel
graphite2-devel
harfbuzz-devel
imlib2-devel
krb5-devel
lcms2-devel
libattr-devel
libcap-devel
libcom_err-devel
libdrm-devel
libffi-devel
libgcrypt-devel
libgpg-error-devel
libICE-devel
libidn-devel
libpng-devel
libselinux-devel
libSM-devel
libstdc++-devel
libtasn1-devel
libtool-ltdl-devel
libuuid-devel
libwayland-client-devel
libwayland-server-devel
libX11-devel
libXau-devel
libxcb-devel
libXdamage-devel
libXext-devel
libXfixes-devel
libXft-devel
libXi-devel
libXrender-devel
libxshmfence-devel
libXxf86vm-devel
mesa-libEGL-devel
mesa-libgbm-devel
mesa-libGL-devel
mesa-libGLU-devel
ncurses-devel
nettle-devel
nss-softokn-freebl-devel
openssl-devel
p11-kit-devel
package avahi-devel is not installed
package keyutils-devel is not installed
package libgcc-devel is not installed
package libgomp-devel is not installed
package mesa
pcre-devel
pixman-devel
readline-devel
sqlite-devel
systemd-devel
xz-devel
zlib-devel
```

That should give you some ideas about the names you need to do:

```
$ sudo dnf install -y ...
```

for the devel header packages.

**Comment by HinTak** [comment]
There are no keyutils-devel  libgcc-devel  libgomp-devel mesa-libglapi-devel packages, and avahi-devel is not needed. (the somewhat mess in the middle ' package ... is not installed' in the middle list).

**Comment by tomlechner** [comment]
I'd like to put the above list in a faq question, but is there an easy way to get a list of "top level" packages, that would automatically pull in dependencies? The above is quite a long list. I don't have Fedora to test on.

**Comment by HinTak** [comment]
Okay, this is a smaller list:

```
cairo-devel
cups-devel
fontconfig-devel
ftgl-devel
glibc-headers
harfbuzz-devel
imlib2-devel
lcms-devel
liblo-devel
libpng-devel
libwiimote-devel
libX11-devel
libXext-devel
libXft-devel
libXi-devel
mesa-libGL-devel
mesa-libGLU-devel
openssl-devel
readline-devel
sqlite-devel
xorg-x11-proto-devel
zlib-devel
GraphicsMagick-c++-devel
libstdc++-devel
freetype-devel
```

This is based on actual header usage, instead of library dependencies like the previous, somewhat edited from the output of:

```
$ grep -h -R '^#include' *  | sort | uniq | grep '<' | grep -v '<lax' | cut -f 2 -d ' ' | perl -p -e 's(<)(/usr/include/)g;s(>)()' | xargs rpm -qf | perl -p -e 's(-[^-]+-[^-]+$)(\n)' | sort | uniq
```

BTW, you have the full "/usr/include/GraphicsMagick/Magick++.h" hard-coded in a few places, which is a bit naughty. I have had to install libwiimote-devel and liblo-devel to get all the headers you used. Those two are optional?

Since this list is based on actual header usage somewhere in your code (okay, you might have some "#ifdef ..." to make them optional) , it is probably considered minimal, compared to the first one I posted.

**Comment by tomlechner** [comment]
Yes, in lax/laxwii.cc there's code that makes wiimotes accessible as an input device, but it is not compiled, documented, or otherwise included in either other laxkit files or Laidout, it's more of an experiment for now, plus I haven't touched it in a few years, it's probably bitrotted a little. If a user uses that file in a project, then you would need libwiimote and liblo, but not otherwise.

**Comment by tomlechner** [comment]
Yes, I'll have to replace the hardcoded GraphicsMagick link.. I might make that a non-optional part of Laidout, but right now, it's only used in the optional Polyptych polyhedron projector/unwrapper.

Also, just to be clear, if someone wants to install all the above packages on Fedora, they would do:
`sudo dnf install -y (that whole list)`
Is that right?

**Comment by HinTak** [comment]
The new list is based on header usage, and where the respective header comes from, so it should be minimal. Most of them fairly obvious and largely the equivalent of your debian apt-get list. You just need to add 

```
gcc-c++
pkgconfig
```

for the fedora equivalent of the first two items in your debian list. Not sure what xutils-dev corresponds to, possibly xorg-x11-proto-devel . "glibc-headers" contains ANSI c headers and is generic to programs using the ansi C library, and libstdc++-devel contains the ANSI c++ headers, and most people who do any program development at all likely already have them installed, does not hurt to include them in the list.

Your debian apt-get list is missing lcms and zlib dependencies compared to my fedora list. Other than that, they are the same now. Here is the updated fedora list:

```
cairo-devel
cups-devel
fontconfig-devel
ftgl-devel
glibc-headers
harfbuzz-devel
imlib2-devel
lcms-devel
liblo-devel
libpng-devel
libwiimote-devel
libX11-devel
libXext-devel
libXft-devel
libXi-devel
mesa-libGL-devel
mesa-libGLU-devel
openssl-devel
readline-devel
sqlite-devel
xorg-x11-proto-devel
zlib-devel
GraphicsMagick-c++-devel
libstdc++-devel
freetype-devel
gcc-c++
pkgconfig
```

**Comment by tomlechner** [comment]
I use xutils-dev for only one thing, the program makedepend to map out compile dependencies. It produces all the "makedepend" files that get used by the Makefiles. Is that in Fedora somewhere, or some other equivalent program?

lcms will be a requirement, but isn't quite used yet.

**Comment by HinTak** [comment]
> sudo dnf install -y (that whole list)

Yes, that should do it. DNF was introduced in Fedora 18, and it has been the default package manager for Fedora since version 22 . For older Fedora's or Redhat's Enterprise Linux, "... yum ..." does the same thing.

**Comment by HinTak** [comment]
On Fedora, makedepend is part of the imake package. (On debian, imake itself is probably lumped under xutils-dev). So that's one more to the list :-).

**Comment by HinTak** [comment]
You have used zlib directly in  laxkit/lax/fontscanner.cc .

**Comment by tomlechner** [comment]
Several other packages depend on zlib in debian, thus the debian list doesn't need it. In Debian it's called zlib1g-dev.. Usually library packages start with "lib", but I guess zlib wants to be different!

Also just committed removal of hard coded links to GraphicsMagick, mentioned Fedora package list in main README.md, and updating files in src/polyptych so all the stuff there actually compiles again.. Seems the subprograms there had bitrotted a little.

**Comment by HinTak** [comment]
Straightly speaking, cairo requires fontconfig requires freetype requires libpng requires zlib, so if you specify cairo, it brings in most of the others. I just checked, "cairo-devel" also brings in libX11-devel, libXext-devel, mesa-libGL-devel, pkgconfig . libX11-devel brings in  xorg-x11-proto-devel . So if you want to be lazy, cairo-devel itself brings in 9 others of among the 28. But since you do use the headers directly, you probably should explicitly specify zlib-devel :-).

**Comment by HinTak** [comment]
> Usually library packages start with "lib", but I guess zlib wants to be different!

It is the other way round :-). zlib was written in the early 80's before all the others, so it is really more that others did not want to follow the zlib example for naming...

**Comment by tomlechner** [comment]
Oh well, that's ok then. Still not sure where the "1g" of "zlib1g" came from.
I guess being explicit in listing the packages has its advantages.

**Comment by tomlechner** [comment]
Added zlib1g-dev to the list and updated "Dev" on the website and in the source to also include the Fedora package list. I also made the main 'make' depend on touchdepends which makes it so you don't have to do 'make depends' before 'make'. I also made Laidout the owner of Laxkit, instead of me personally.
