### ISSUE TITLE
Meson build system

### ISSUE THREAD

**Issue by eszlari** [Laidout/laidout#20]
Has it been considered to move to the Meson build system?

https://mesonbuild.com

**Comment by tomlechner** [comment]
Their docs say "The main design point of Meson is that every moment a developer spends writing or debugging build definitions is a second wasted." I am absolutely in agreement about that sentiment! Changing build systems would absolutely be that. It would also add another dependency, which I try to avoid without a very good reason.

Maybe some day if Laidout is ever ported to Windows, and Meson is somehow easier to wrangle dependencies with, maybe it would be worth it. Long way to go before that, though.

**Comment by tomlechner** [comment]
So, keeping the current build system, though perhaps open to changing at some point if tech debt for the current custom system gets too high.

**Comment by eszlari** [comment]
> It would also add another dependency, which I try to avoid without a very good reason.

Meson only needs python3 (and it can be installed through pip), and since there are already some python scripts in the tree, this wouldn't really add a new dependency.
