### ISSUE TITLE
exporting to pdf doesn't show overflow

### ISSUE THREAD

**Issue by Falano** [Laidout/laidout#29]
Hi!
Thanks for developing laidout, it's very useful. I used it to print a couple small booklets at home, it went great.
I now have another project, which uses double page pictures: each file I have actually takes two pages. I imported it to laidout (btw a "import multiple files but only put them in the project once every X pages" would be nice for longer projects of this type), and the Papers view shows what I expect.
But when I export to pdf, it only shows the left part of the picture, with the right side always being blank, like some kind of page clipping were on (except page clipping doesn't react like that in Papers view either). I assume it's because the picture is technically held on the left page and only overflows on the right one.
See attached picture with laidout on the left (the result I want) and the exported pdf on the right (the result I get).

I'm using laidout appimage 0.097.1 on Ubuntu 22.04.1 (when I start laidout, it tells me it could not load the gegInodes.so plugin)

![Screenshot from 2023-05-17 10-42-01](https://github.com/Laidout/laidout/assets/15685823/b2bcbfa8-0838-4398-bef4-7d2bdc05a12f)

**Comment by tomlechner** [comment]
Great that you are using Laidout!

For importing every X, I sort of coded that already but didn't document it. Testing it just now, it's slightly buggy. The gist is that in "Exactly this many" if you write `1/2` it will drop an image then skip 2 pages. The buggy part is that `1/1` doesn't drop 1 and skip 1. I think I meant for `1/n` to be one image every n pages... I need to fix that! Really that whole dialog needs to be redone, it is a mess.

For the page bleed thing, I thought I had it so any images that bleed over in the "Page" view should be clipped and drawn appropriately in the exported "Papers" view. Apparently bugged! I'll look into it. 

Is it just pdf that's like that? If you export to, say, SVG or image is it also wrong?

**Comment by tomlechner** [comment]
Also it would appear my travis CI builder is broken. I know there is more recent than October 2021!

Not sure why the geglnodes.so is not loading, it loads for me using the appimage, as long as there's no other geglnodes.so in known search paths.

From a terminal, could you run this command and post the result? (replace the appimage with the right name)
```
./Laidout-ae6b35e-x86_64.AppImage 2> temp.txt
grep 'dlerror\|geglnodes' temp.txt
```

**Comment by tomlechner** [comment]
Fixed the import every nth, so "m/n" in "Exactly this many" means import m images on every nth page (but always put some on the "start page").

Still working on the other stuff.

**Comment by Falano** [comment]
Hi!
for the geglnodes, it told me this:
loading plugin /tmp/.mount_Laidou9xl8CN/usr/share/laidout/0.097.1/plugins/geglnodes.so...
dl opened... dlerror: addwindow: style: ffffffffc0260c08

(I'm not sure what it does, I mentioned it on the off-chance it was linked to the double page export issue)


other export formats:
I think I did not have that before (I'm not sure), but now changing export formats is buggy. 
I think what happens is: 
- changing the export format from Image to anything else (using the export window) often makes it crash when I release the export format list (that may depend on the export options or on whether I have successfully exported to image or another format before). 
- I can change back to pdf by going to the ~/.config/laidout/0.097.1/autolaidoutrc file and manually changing "  last_format      Image" to "  last_format      Pdf 1.4" (I also tried svg, it worked, so presumably it works for all). 
- Once I've changed through autolaidoutrc, I need to export once in that format (and exit laidout cleanly without crashing it), and then I can change the export format using the export window. 
- If I changed export format through autolaidoutrc and try to change format using the export window without having successfully exported at least once before, it crashes when I release the export format list.

Image (and svg) exports double pages fine, but pdf still only exports half. When I tried, Image via ghostscript failed (when I click export, it thinks a bit, then laidout crashes; last line of temp.txt says "Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...")
When it crashes due to changing the export format, last line of temp.txt is "Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"..." too.

I tested the new 1/n, it works great so far!

**Comment by tomlechner** [comment]
I think I got most of the Export Dialog crashing fixed. I'd recommend deleting your `autolaidoutrc` file.

Partially fixed (I hope) pdf object bleed for `Papers` layout. In testing, it looks like when exporting `Singles`, the pdf has the wrong page size.

geglnodes.so erroring is unrelated to the other issues. `dl opened... dlerror: addwindow: style: ffffffffc0260c08` means a debugging message somewhere is outputting garbage characters to the console shortly after the "dlerror:" part, which may or may not be related to the actual dl opening.. So, still unsure why the geglnodes.so is not loading.. does it load for the non-appimage version?

**Comment by Falano** [comment]
Export dialog and pdf export with double page pictures: Great, thanks! It works on my end.
Wrong page size in singles mode: It's not just pdf, it does that also with the Images export format when I use double page pictures (I haven't tested the others but I assume it's the same).
Geglnodes: With the non-appimage version, I have no geglnodes error, it loads fine.

**Comment by tomlechner** [comment]
Located the problem, going to have to think about how best to fix it.. some bad 15 year old assumptions coming back to haunt me! It affects all non-Single impositions by applying a wrong default paper group to non-PaperLayout exports.

As a work around, you can use the Paper Group tool to create a paper group with a half paper size, place that over the page, then export. It will use that custom paper group instead of the default paper group, which for booklets defaults incorrectly to the whole paper, not just single pages.

**Comment by tomlechner** [comment]
Hopefully fixed wrong page size on export. It affected every export filter.
Closing, and feel free to let me know of other issues, bugs, features you come across!
