### ISSUE TITLE
"make clean" left overs

### ISSUE THREAD

**Issue by HinTak** [Laidout/laidout#5]
"make clean" does not quite clean - you can see that by issuing a "git status --ignored" to show left over files which are in .gitignore .

 It is useful to do "git status --ignored" once in a while to see left over files which are configured to be ignored, but shouldn't be there.

**Comment by tomlechner** [comment]
I added an extra clean target, it seems it wasn't calling clean for src/polyptych. Otherwise, for me it seems like all that remains are files named "makedepend" or "makedepend.bak", which I'm ok with not being cleaned.

**Comment by tomlechner** [comment]
Added a dist-clean target to remove even the makedepend and makedepend.bak files.
