### ISSUE TITLE
VillaPazza woff anomaly.

### ISSUE THREAD

**Issue by HinTak** [Laidout/laidout#6]
I had a working private svg font example from Adobe so it is quick to adapt that to your VillaPazza-take1.woff . Interestingly, your font works under icecat-38.7.1 but not firefox-45.0.2 (and they are supposed to be related and not too far off).

chrome's behavior seems to depends on not having --disable-accelerated-video , which is annoying.

**Comment by HinTak** [comment]
If you just duplicate the whole 'cmap_format_4 platformID="0" platEncID="3" language="0"' entry as 'cmap_format_4 platformID="3" platEncID="1" language="0"', it would work.

Bugs elsewhere(!), not your fault:

See https://github.com/khaledhosny/ots/issues/106 , https://github.com/khaledhosny/ots/issues/107 , https://lists.w3.org/Archives/Public/public-webfonts-wg/2016Jan/0000.html , https://github.com/nodebox/opentype.js/issues/185 .

**Comment by HinTak** [comment]
Filed at firefox's bug tracker also.

https://bugzilla.mozilla.org/show_bug.cgi?id=1269187

**Comment by tomlechner** [comment]
At some point I'll probably make a public repository for helper scripts used to make the Villa Pazza font (image -> svg chopper -> ttx builder -> ttx). The font itself is somewhat in the "embarassing" state of development. ttx compiles without errors, but there are a lot of glyph spacing issues I haven't figured out yet. Not quite ready to release it into the world, and still working on the opentype-svg renderer for Laidout.

**Comment by HinTak** [comment]
> there are a lot of glyph spacing issues

Yes, I ran FontValidator against it and there are piles on warnings :-). There is a particular one about that:

E2135   The xAvgCharWidth field does not equal the calculated value     actual = 629, calc = 414

I'll send the whole thing to you via e-mail.

**Comment by HinTak** [comment]
The bounding box for almost all glyphs is also wrong....

**Comment by tomlechner** [comment]
Yeah, I was kind of hurrying to get something visible to show at LGM. Thanks for the list, it gives me lots of things to add to my todo list!

I tried FontValidator from git (https://github.com/Microsoft/Font-Validator), and it tells me XML viewing is not implemented on non-windows, and also does not let me copy the filename of the xml file, I have to retype it to get at the file. It also says SVG is not an opentype table, but I see it is listed in what you emailed. Is there some other newer FontValidator version somewhere?

As a shortcut to get a minimally functional glyf table, I just grabbed the bottom most color layer of the svg glyph, and used that for the outline of the fallback glyf table, but still need to implement better path conversion from the original traced image svg. I think I read somewhere that the SVG glyph metrics should be the same as the glyf metrics, though does that mean bounding box, or just advance values? (just one of many things I don't yet understand about font files)

**Comment by tomlechner** [comment]
Also I see that the list you sent accepts SVG, but claims CPAL is not an opentype table.

**Comment by HinTak** [comment]
https://github.com/HinTak/Font-Validator is much newer :-). Yes, the CPAL one is straight, need to look into that...

**Comment by HinTak** [comment]
Oh, xml viewing isn't falling working on my version either, todo.

Can you not match the svg bound box to the glyf one? I haven't read that part of the spec either, but that's probably safest.

**Comment by tomlechner** [comment]
Closing this issue in favor of #25 .
