### ISSUE TITLE
Little changes to make laidout build on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by spaceChRiS** [Laidout/laidout#9]
I encountered basically two errors while trying to build laidout. Here's what I had to change to make it build together with additional information.

I am running Ubuntu 16.04.1 with gegl 0.3.25 from the “otto-kesselgulasch” ppa and python 2.7.12.

The first issue was that the ``gegl-paramspecs.h`` file was not found. It resides in ``/usr/include/gegl-0.3/``, and the include path was correct during compilation. Therefore, it worked by removing the ``gegl/``-prefix in the ``#include`` directive. I don't know why the path seems to differ among gegl installations and unfortunately I don't know a general fix.

    diff --git a/src/plugins/geglnodes.cc b/src/plugins/geglnodes.cc
    index d52581f..384a73b 100644
    --- a/src/plugins/geglnodes.cc
    +++ b/src/plugins/geglnodes.cc
    @@ -20,7 +20,7 @@
     #include "geglnodes.h"
     #include "svg/svgnodes.h"
     
    -#include <gegl/gegl-paramspecs.h>
    +#include <gegl-paramspecs.h>
     
     #include <iostream>
     #define DBG

The second issue is with icon generation, that inkscape got offset parameters as float-formatted inputs, i.e. “xxx.0”, which it did not accept. It only happened in one of the scripts. A hard typecast for every parameter solved the issue (not too elegant but works). 

    diff --git a/configure b/configure
    old mode 100644
    new mode 100755
    diff --git a/src/icons/makeimages.py b/src/icons/makeimages.py
    index a3a2d6d..81861d5 100755
    --- a/src/icons/makeimages.py
    +++ b/src/icons/makeimages.py
    @@ -125,14 +125,14 @@ for name in names :
         H=int(float(subprocess.check_output("inkscape -I "+name+" -H icons.svg", shell=True)))
 
         print ("raw inkscape coords xywh: "+str(X)+","+str(Y)+" "+str(W)+","+str(H))
    -    x1 = int(X/HALFPPU)*HALFPPU
    +    x1 = int(int(X/HALFPPU)*HALFPPU)
         #y1 = int(Y/HALFPPU)*HALFPPU
         print ('doc height: '+str(DOCUMENTHEIGHT))
    -    y1 = DOCUMENTHEIGHT*PPU-int(Y/HALFPPU)*HALFPPU-HALFPPU
    +    y1 = int(DOCUMENTHEIGHT*PPU-int(Y/HALFPPU)*HALFPPU-HALFPPU)
         renderwidth =bitmapw*(1+int(W/HALFPPU))
         renderheight=bitmapw*(1+int(H/HALFPPU))
    -    x2=x1+HALFPPU*(1+int(W/HALFPPU))
    -    y2=y1+HALFPPU*(1+int(H/HALFPPU))
    +    x2=int(x1+HALFPPU*(1+int(W/HALFPPU)))
    +    y2=int(y1+HALFPPU*(1+int(H/HALFPPU)))
     
         print ("x1,y1:"+str(x1)+","+str(y1)+"  x2,y2:"+str(x2)+"x"+str(y2))
         print ("icon coords x1,y1:"+str(int(x1*2/PPU)) + "," + str(int(y1*2/PPU)))

Even if the second issue may not happen with other python versions (maybe they did some changes in number handling), it seems beneficial to generally fix this. About the first one, I have no idea.

**Comment by tomlechner** [comment]
Thanks! Gegl include and configure permission committed. Looks like I wasn't paying attention with configure on last commit, accidentally wiped the exec flag!

Odd that the image generator works on my system, where Inkscape doesn't seem to care about floating point numbers (and thus subpixel accuracy). Fraction part should always be 0 here, but odd that it fails. Which Inkscape are you using? I'm assuming numbers use periods, not commas in that system call?

There's 3 different makeicon.py variations to correct, I should have time to get those in shape later today.

An uncompleted task is for Laidout to make icons directly from the master icons.svg file as needed, but my svg importer isn't good enough yet, so still stuck with my rather unpleasant makeicons.py+Inkscape thing.

**Comment by spaceChRiS** [comment]
Oh, that exec one I forgot :-)

Hm, image generator, good catch, did not think about the language. It works when I replace the period by a comma. German language setting here, but I think that's an error on the inkscape side, it should definitely accept the period. But if you can fix it on your side: even better. Inkscape 0.92.2, btw.

It happens only to the``makeicon.py`` that I changed, the others output integers, don't know why.

What I found is that while the icon generation is running, only one thread is used. Parallelization may speed up the process tremendously.

**Comment by tomlechner** [comment]
The other icon scripts and icon files were still pre Inkscape 0.92, which apparently I've neglected to update! So they don't have the `HALFPPU=PPU/2`. I guess the /2 turns it into a float, but the other 2 still used only + and *, which keeps the numbers ints.

By the way, added a zip with the icons just in case here:
https://github.com/Laidout/laidout/releases/download/0.096/laidout-icons.zip

**Comment by tomlechner** [comment]
Ok, so those scripts and icon files are fixed now, using the forced int casting. Not sure why the line using setlocale wasn't fixing it. Anyway, should be ok now!

I'll have to think about threading.. The script would have to fork in batches up to a specified number of threads. I'd have to study up on python forking. Patches welcome!

**Comment by tomlechner** [comment]
Going to assume done!
